package cn.gtcommunity.epimorphism.api.pattern;

import cn.gtcommunity.epimorphism.api.EPAPI;
import cn.gtcommunity.epimorphism.api.block.IGlassTierBlockState;
import cn.gtcommunity.epimorphism.api.block.impl.WrappedIntTired;
import cn.gtcommunity.epimorphism.api.pattern.predicates.TierTraceabilityPredicate;
import gregtech.api.pattern.PatternStringError;
import gregtech.api.pattern.TraceabilityPredicate;
import gregtech.api.util.BlockInfo;
import net.minecraft.block.state.IBlockState;

import java.util.Comparator;
import java.util.LinkedList;
import java.util.function.Supplier;

import static cn.gtcommunity.epimorphism.api.EPAPI.*;

public class EPTraceabilityPredicate {

    public static Supplier<TraceabilityPredicate> EP_GLASS = () -> new TraceabilityPredicate(blockWorldState -> {
        IBlockState blockState = blockWorldState.getBlockState();
        if (EPAPI.EP_Glass.containsKey(blockState)) {
            IGlassTierBlockState stats = EPAPI.EP_Glass.get(blockState);
            Object currentGlass = blockWorldState.getMatchContext().getOrPut("CasingType", stats);
            if (!currentGlass.equals(stats)) {
                blockWorldState.setError(new PatternStringError("epimorphism.multiblock.pattern.error.glasses"));
                return false;
            }
            blockWorldState.getMatchContext().getOrPut("VABlock", new LinkedList<>()).add(blockWorldState.getPos());
            return true;
        }
        return false;
    }, () -> EPAPI.EP_Glass.entrySet().stream()
            // sort to make autogenerated jei previews not pick random coils each game load
            .sorted(Comparator.comparingInt(entry -> entry.getValue().getGlassTier()))
            .map(entry -> new BlockInfo(entry.getKey(), null))
            .toArray(BlockInfo[]::new))
            .addTooltips("epimorphism.multiblock.pattern.error.glasses");

    public static Supplier<TierTraceabilityPredicate> EP_MACHINE_CASINGS = () -> new TierTraceabilityPredicate(MAP_MACHINE_CASING,"MachineCasingType",null);
    public static Supplier<TierTraceabilityPredicate> EP_CP_CASING = () -> new TierTraceabilityPredicate(MAP_CP_CASING,
            Comparator.comparing((s) -> ((WrappedIntTired)MAP_CP_CASING.get(s)).getIntTier()),"ChemicalPlantCasing",null);
    public static Supplier<TierTraceabilityPredicate> EP_CP_TUBE = () -> new TierTraceabilityPredicate(MAP_CP_TUBE,
            Comparator.comparing((s) -> ((WrappedIntTired)MAP_CP_TUBE.get(s)).getIntTier()),"ChemicalPlantTube",null);
}
