package cn.gtcommunity.epimorphism.api.unification;

import cn.gtcommunity.epimorphism.api.unification.materials.*;
import gregtech.api.unification.material.Material;

public class EPMaterials {
public EPMaterials() {}

    //  First Degree Materials
    public static Material GrapheneOxide;
    public static Material Hydrazine;
    public static Material BerylliumOxide;
    public static Material HydrogenPeroxide;
    public static Material TungstenTrioxide;
    public static Material HexagonalBoronNitride;
    public static Material CubicBoronNitride;
    public static Material BoricAcid;
    public static Material BoronTrioxide;
    public static Material BoronTrifluoride;
    public static Material LithiumHydride;
    public static Material LithiumTetrafluoroborate;
    public static Material Diborane;
    public static Material Borazine;
    public static Material BoronTrichloride;
    public static Material Trichloroborazine;
    public static Material AmorphousBoronNitride;
    public static Material Heterodiamond;
    public static Material CubicHeterodiamond;
    public static Material CarbonNanotube;
    public static Material SilverTetrafluoroborate;
    public static Material TrimethyltinChloride;
    public static Material SilverChloride;
    public static Material ChloroplatinicAcid;
    public static Material PotassiumTetrachloroplatinate;
    public static Material NickelTriphenylphosphite;
    public static Material NickelChloride;
    public static Material PhosphorusTrichloride;
    public static Material AmmoniumSulfate;
    public static Material AmmoniumPersulfate;
    public static Material HydroxylamineDisulfate;
    public static Material Hydroxylamine;
    public static Material AmmoniumNitrate;
    public static Material ThalliumSulfate;
    public static Material ThalliumChloride;
    public static Material IodizedBrine;
    public static Material IodineBrineMixture;
    public static Material BrominatedBrine;
    public static Material IodineSlurry;
    public static Material SodiumIodate;
    public static Material SodiumIodide;
    public static Material SodiumHypochlorite;
    public static Material SodiumPeriodate;
    public static Material AcidicBrominatedBrine;
    public static Material BromineSulfateSolution;
    public static Material OverheatedBromineSulfateSolution;
    public static Material WetBromine;
    public static Material DebrominatedWater;
    public static Material PalladiumChloride;
    public static Material PalladiumOnCarbon;
    public static Material PotassiumPermanganate;
    public static Material PotassiumManganate;
    public static Material TinChloride;
    public static Material SilverOxide;
    public static Material SodiumFluoride;
    public static Material ZnFeAlClCatalyst;
    public static Material SodiumNitrite;
    public static Material SodiumNitrate;
    public static Material FluoroboricAcid;
    public static Material BenzenediazoniumTetrafluoroborate;
    public static Material GalliumTrichloride;
    public static Material AluminiumTrichloride;
    public static Material Trimethylgallium;
    public static Material AluminiumHydroxide;
    public static Material Alumina;
    public static Material GalliumTrioxide;
    public static Material GalliumNitride;
    public static Material Fullerene;
    public static Material GeodesicPolyarene;
    public static Material TiAlCatalyst;
    public static Material PotassiumCyanide;
    public static Material PotassiumBromide;
    public static Material BismuthVanadate;
    public static Material BismuthVanadateSolution;
    public static Material AmmoniumVanadate;
    public static Material VanadiumSlag;
    public static Material BismuthNitrateSolution;
    public static Material SodiumVanadate;
    public static Material VanadiumWasteSolution;
    public static Material SodiumBromide;
    public static Material WhitePhosphorus;
    public static Material RedPhosphorus;
    public static Material VioletPhosphorus;
    public static Material BlackPhosphorus;
    public static Material BluePhosphorus;
    public static Material Wollastonite;
    public static Material Phosphorene;
    public static Material PhosphorylChloride;
    public static Material Phosphine;
    public static Material CopperChloride;
    public static Material LithiumHydroxide;
    public static Material LithiumAmalgam;
    public static Material HexafluorideEnrichedNaquadahSolution;
    public static Material XenonHexafluoroEnrichedNaquadate;
    public static Material EnrichedNaquadahResidueSolution;
    public static Material XenoauricFluoroantimonicAcid;
    public static Material GoldChloride;
    public static Material BromineTrifluoride;
    public static Material GoldTrifluoride;
    public static Material NaquadriaCaesiumfluoride;
    public static Material AcidicNaquadriaCaesiumfluoride;
    public static Material NitrosoniumOctafluoroxenate;
    public static Material NaquadriaCaesiumXenonnonfluoride;
    public static Material RadonNaquadriaOctafluoride;
    public static Material CaesiumXenontrioxideFluoride;
    public static Material RadonTrioxide;
    public static Material CaesiumFluoride;
    public static Material XenonTrioxide;
    public static Material HexafluorideNaquadriaSolution;
    public static Material NaquadriaResidueSolution;
    public static Material RadonDifluoride;
    public static Material HeavyAlkaliChlorideSolution;
    public static Material StannicChloride;
    public static Material RubidiumChlorostannate;
    public static Material CaesiumChlorostannate;
    public static Material GermaniumDioxide;
    public static Material RoastedSphalerite;
    public static Material ZincRichSphalerite;
    public static Material ZincOxide;
    public static Material WaelzOxide;
    public static Material WaelzSlag;
    public static Material ImpureGermaniumDioxide;
    public static Material GermaniumTetrachloride;
    public static Material MolybdenumTrioxide;
    public static Material LeadChloride;
    public static Material PerrhenicAcid;
    public static Material AmmoniumPerrhenate;
    public static Material NiobiumPentoxide;
    public static Material TantalumPentoxide;
    public static Material CalciumDifluoride;
    public static Material ManganeseDifluoride;
    public static Material CalciumCarbide;
    public static Material CalciumHydroxide;

    //  Organic Chemistry Materials
    public static Material KaptonK;
    public static Material KaptonE;
    public static Material Edot;
    public static Material Polystyrene;
    public static Material PolystyreneSulfonate;
    public static Material PedotPSS;
    public static Material PMMA;
    public static Material PedotTMA;
    public static Material TetramethylammoniumHydroxide;
    public static Material PotassiumHydroxide;
    public static Material PotassiumBromate;
    public static Material MalonicAcid;
    public static Material ChloroaceticAcid;
    public static Material Trichloroethylene;
    public static Material Dichloroethane;
    public static Material HydrobromicAcid;
    public static Material Butanediol;
    public static Material Diacetyl;
    public static Material EthyleneGlycol;
    public static Material SulfurDichloride;
    public static Material AcetoneCyanohydrin;
    public static Material ParaXylene;
    public static Material Cycloparaphenylene;
    public static Material Dichlorocyclooctadieneplatinium;
    public static Material Diiodobiphenyl;
    public static Material Bipyridine;
    public static Material PalladiumBisdibenzylidieneacetone;
    public static Material Octene;
    public static Material Acetylene;
    public static Material Cyclooctadiene;
    public static Material Pyridine;
    public static Material Formaldehyde;
    public static Material Dibenzylideneacetone;
    public static Material Benzaldehyde;
    public static Material BenzoylChloride;
    public static Material ThionylChloride;
    public static Material Polyetheretherketone;
    public static Material Difluorobenzophenone;
    public static Material Hydroquinone;
    public static Material Resorcinol;
    public static Material Fluorobenzene;
    public static Material Fluorotoluene;
    public static Material Kevlar;
    public static Material ParaPhenylenediamine;
    public static Material TerephthaloylChloride;
    public static Material NMethylPyrrolidone;
    public static Material Nitroaniline;
    public static Material Durene;
    public static Material PyromelliticDianhydride;
    public static Material Aminophenol;
    public static Material Aniline;
    public static Material Oxydianiline;
    public static Material Dimethylformamide;
    public static Material PhthalicAnhydride;
    public static Material BiphenylTetracarboxylicAcidDianhydride;
    public static Material Bistrichloromethylbenzene;
    public static Material Tetrabromoethane;
    public static Material TerephthalicAcid;
    public static Material GammaButyrolactone;
    public static Material Methylamine;
    public static Material Trimethylaluminium;
    public static Material Benzophenanthrenylacetonitrile;
    public static Material Methylbenzophenanthrene;
    public static Material BromoSuccinimide;
    public static Material Succinimide;
    public static Material SuccinicAcid;
    public static Material MaleicAnhydride;
    public static Material Naphthaldehyde;
    public static Material Butanol;
    public static Material Bromobutane;
    public static Material Cyanonaphthalene;
    public static Material Triphenylphosphine;
    public static Material Ethylanthraquinone;
    public static Material Ethylanthrahydroquinone;
    public static Material Ethylenediamine;
    public static Material TetrasodiumEDTA;
    public static Material EthylenediaminetetraaceticAcid;
    public static Material TetramethylammoniumChloride;
    public static Material Trimethylamine;
    public static Material Pyrocatechol;
    public static Material NitrylFluoride;

    //  Unknown Composition Materials
    public static Material BZMedium;
    public static Material EDP;
    public static Material RichNitrogenMixture;
    public static Material RichAmmoniaMixture;
    public static Material BlazingPyrotheum;
    public static Material GelidCryotheum;
    public static Material CoACABCatalyst;
    public static Material PhosphoreneSolution;
    public static Material MethylamineMixture;
    public static Material MolybdenumFlue;
    public static Material TraceRheniumFlue;

    //  Machine Casing Materials
    public static Material Inconel625;
    public static Material HastelloyN;


    //  Biological Production Line
    /*public static Material ArtificialBaseX;
    public static Material ArtificialBaseZ;
    public static Material ;
    public static Material
    public static Material
    public static Material*/

    //  Range: 24000-28000
    public static void init() {
        EPMaterialPropertyAddition.init();
        EPMaterialFlagAddition.init();
        EPFirstDegreeMaterials.register();
        EPOrganicChemistryMaterials.register();
        EPUnknownCompositionMaterials.register();
        EPMachineCasingMaterials.register();
    }

}
